# Generated by Django 3.2 on 2024-04-30 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
